// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmvm4SjAcb_xRv25CO1UMvIIEvRgSh27U',
    appId: '1:958783693601:android:9dd932325905f6c5df9460',
    messagingSenderId: '958783693601',
    projectId: 'chatify-111',
    storageBucket: 'chatify-111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpQdTqf7OYxWl36nCEEbnL_yWqAMbcT0',
    appId: '1:958783693601:ios:f1076124a4c85aa4df9460',
    messagingSenderId: '958783693601',
    projectId: 'chatify-111',
    storageBucket: 'chatify-111.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVG1a6rv6WRsPXzB19qkAVJp5_Z68cT20',
    appId: '1:958783693601:web:2067091aa850b8b6df9460',
    messagingSenderId: '958783693601',
    projectId: 'chatify-111',
    authDomain: 'chatify-111.firebaseapp.com',
    storageBucket: 'chatify-111.firebasestorage.app',
    measurementId: 'G-SYSLDLWGXQ',
  );
}
